# Determines the default locale in the absence of other locale related environment variables.
LANG=en_GB.UTF-8
# Format of interactive words and responses.
LC_MESSAGES=en_GB.UTF-8
# Character classification and case conversion.
LC_CTYPE=@LOCALE@
# Numeric formatting.
LC_NUMERIC=@LOCALE@
# Date and time formats.
LC_TIME=@LOCALE@
# Monetary formatting.
LC_MONETARY=@LOCALE@
# Default measurement system used within the region.
LC_MEASUREMENT=@LOCALE@
# Convention used for formatting of street or postal addresses.
LC_ADDRESS=@LOCALE@
# Conventions used for representation of telephone numbers.
LC_TELEPHONE=@LOCALE@
# Default paper size for region.
LC_PAPER=@LOCALE@
# Collation order.
LC_COLLATE=@LOCALE@
